# Generated by Django 2.1.4 on 2018-12-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
